# Generated by Django 5.2.1 on 2025-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
